# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.IntegerField(default=1)),
                ('date_creation', models.DateField()),
                ('description', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('access', models.BooleanField()),
                ('users_id', models.IntegerField(default=1)),
                ('version_last', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
