# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20171205_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Template')),
            ],
        ),
    ]
