# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20171206_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='date_creation',
            field=models.DateTimeField(),
        ),
    ]
